### PR TITLE
feat: parsed options

### PR DESCRIPTION
**Pull request by eyalpost**
Properly parse option values into objects in addition to the regular option parsing. 
Repeated options are preserved as well as repeated fields within nested options.
Parsed options are kept in a `parsedOptions` field on every level (message, field etc.)

### CODE REVIEW

**Comment by alexander-fenster** [comment]
Thanks @eyalpost! We'll take a look soon :)

**Comment by eyalpost** [comment]
Any news? We'd really like to see this being merged

**Comment by Musiqua** [comment]
This PR solves a problem of ours using the grps.gateway.protoc_gen_swagger_options_openapiv2_schema annotation for required fields, so we would also like to see this being merged as soon as possible.

**Comment by mavrick** [comment]
any updates on this?

**Comment by fenos** [comment]
Any Update?

**Comment by fenos** [comment]
🎉 changes approved!! Can we please merge and cut a release 🙏 

BloomRPC will benefit hugely on this

**Comment by guyisra** [comment]
@alexander-fenster  any updates on this?

**Comment by kostyay** [comment]
any updates?

**Comment by aSapien** [comment]
hi, is there a plan on accepting this pr?

**Comment by alexander-fenster** [comment]
I merged in the latest master and made sure the tests pass. We'll review the code changes on our next review meeting.

**Pull request merged**
