### PR TITLE
Add support for buffer configuration.

### PR DESCRIPTION
**Pull request by tinchoz49**
Hi everyone!

## Description

This PR add support for configuring dynamically a Buffer util.

Similar to what you can do with the util.Long: https://github.com/protobufjs/protobuf.js#browserify-integration

```javascript
protobuf.util.Buffer = Buffer;
protobuf.configure();
```

## Background

There is a lot of Node.js modules that only works with the Node Buffer implementation but also we can use it in the browser thanks to the [feross/buffer](https://github.com/feross/buffer).

Many bundle tools like Webpack, Browserify and Parcel already includes a node built-in Buffer implementation and we can use it in protobufjs to encode/decode bytes in similar structures (Buffer) between Node and the browser.

### CODE REVIEW

**Comment by alexander-fenster** [comment]
@tinchoz49 Can you please fix the CI? Thanks!

**Comment by tinchoz49** [comment]
Fixed

**Comment by tinchoz49** [comment]
Will fix: https://github.com/protobufjs/protobuf.js/issues/1239

**Comment by dpaez** [comment]
Any update on this?

Great lib by the way!

**Comment by richburdon** [comment]
@alexander-fenster we're depending currently on this fork -- is it likely to get merged soon?

Thanks very much.

**Comment by richburdon** [comment]
Folks any chance you can create a new npm release for this:

https://github.com/protobufjs/protobuf.js/releases

**Pull request merged**
