### PR TITLE
fix: remove eval usage so that chrome extension MV3 can run properly

### PR DESCRIPTION
**Pull request by AntiMoron**
AS POST TITLE.

I think this can be published as an alpha version for more tests.

### CODE REVIEW

**Review by Jennal — APPROVED** [review]

**Comment by AntiMoron** [comment]
The latest Chrome(currently 118.0.5993.117) is blocking js that contains 'eval' now, which may result in blank screen.

image

**Comment by AntiMoron** [comment]
Sorry for disturbing. I'm willing to push the progress.

@dcodeIO 
@alexander-fenster 
@bcoe

**Review by tsemachh — APPROVED** [review]

**Comment by AntiMoron** [comment]
Let's see how ChatGPT judge it:

image

image

**Comment by butoramatus** [comment]
Helo, @AntiMoron do you have any updates on this issue? 
@dcodeIO @alexander-fenster @bcoe do you plan to move this forward? 
Thank you!

**Comment by AntiMoron** [comment]
> Helo, @AntiMoron do you have any updates on this issue? @dcodeIO @alexander-fenster @bcoe do you plan to move this forward? Thank you!

No, I think I've done the coding & testing part, now I'm looking for core members to merge. Thanks for supporting!

**Comment by Jennal** [comment]
Hi, it has been a month since the code commited. The code has been thoroughly reviewed and is clean and easy to verify. I kindly request your attention to address this matter at your earliest convenience.

**Comment by AntiMoron** [comment]
anyone with write access spend sometime on reviewing this?
@dcodeIO 
@robin-anil @murgatroid99 @JustinBeckwith

**Comment by emillime** [comment]
Update on this one?

**Comment by AntiMoron** [comment]
> Update on this one?

Sadly, still waiting for someone to review this.

**Comment by LivingstonPradeep** [comment]
Still waiting on this!!

**Comment by graham-atom** [comment]
any updates here?

**Comment by graham-atom** [comment]
@alexander-fenster

**Comment by zhanzekun** [comment]
any updates ??

**Comment by zhanzekun** [comment]
I'm going to fork it, I can't stand it anymore. The repository owner seems unwilling to accept any changes, right?

**Comment by GG-Creations** [comment]
any news? this eval must go please

**Review by alexander-fenster — APPROVED** [review]

**Comment by alexander-fenster** [comment]
I can merge this one but we'll need to ask @sofisl or someone else from Google with release access to coordinate the release and actually release it. If there's some other fixes that need to be taken care of we could do it too.

Note: I don't work with anything related to protobuf.js anymore, might find some time on regular maintenance and merging PRs like this one but don't want to make releases because it normally requires more testing (with Google libraries) that I can realistically handle.

**Comment by Reinmar** [comment]
Also cc @danielbankhead :pray: :pleading\_face:   
  
Having that `eval()` is causing tons of problems for consumers of our lib (which depends on protobuf).

**Comment by AntiMoron** [comment]
@All Published in version 7.5.0 :tada:

**Comment by Witoso** [comment]
This requires a release of `@protobufjs/inquire`. Whomever done the `7.5.0`, please release subpackages with changes as well 🙏

**Comment by tobiasweibel** [comment]
> @ALL Published in version 7.5.0 🎉

@alexander-fenster can you please have a look again on the build process? As written above `@protobufjs/inquire` wasn't released even though mentioned in the release notes (https://github.com/protobufjs/protobuf.js/releases/tag/protobufjs-v7.5.0).

**Pull request merged**
