### PR TITLE
Static .pbtxt decode support (#957)

### PR DESCRIPTION
**Pull request by lutzroeder**

### CODE REVIEW

**Comment by jackalcooper** [comment]
Hi, Lutz. Thanks for your great work on this feature. 
I tried to use branch `pbtxt` to decode but I got `decodeText is not a function`. I'm wondering how can I verify or decode pbtxt with current codebase.

**Comment by lutzroeder** [comment]
@jackalcooper what steps are you using to reproduce this error? [Netron](https://github.com/lutzroeder/netron/blob/master/tools/tf) has a few samples how this is being used.

**Comment by jackalcooper** [comment]
@lutzroeder 
Here is the code:
```
protobuf.load("path_to.proto", function(err, root) {
    var ProtoDef = root.lookupType("ProtoDef");
    var payload = "net: {}";
    var errMsg = ProtoDef.decodetext(payload)
```

**Comment by jackalcooper** [comment]
Do I have to use cli to generate the code?

**Comment by lutzroeder** [comment]
Yes, currently only `--static-module` is supported.

**Comment by lutzroeder** [comment]
@JustinBeckwith, any advise on how to get this PR reviewed and merged?

**Comment by JustinBeckwith** [comment]
I am *very* new to this project, and mostly here helping triage and push buttons :) @dcodeIO, @nicolasnoble and @murgatroid99 are the actual experts.

**Comment by dcodeIO** [comment]
One thing that bothers me about this is that I expect most users to use the library for binary data and I am not sure in general where text format is useful on the web. This makes me question whether adding a new code path that remains unused in 99% of cases, from the minimal build upwards, is worth it. Is there maybe a way to make this an extension, similar to `ext/descriptor`?

**Comment by lutzroeder** [comment]
@dcodeIO Moved the code so `dist` won't be impacted and the text reader in `ext/prototxt` can be loaded separately for browser.  Looks good or are there other recommended changes?

**Comment by jackalcooper** [comment]
@dcodeIO It is more than useful when building web tools for machine learning frameworks.

**Comment by lutzroeder** [comment]
@dcodeIO, @nicolasnoble and @murgatroid99, what are next steps to get this PR reviewed and merged?

**Comment by julien-c** [comment]
I can understand why one wouldn't want to merge this in the main codepath but we should at least make it easy to find and use if needed.

**Comment by lutzroeder** [comment]
@julien-c @dcodeIO's comment has already been addressed and code moved to `ext`. Also, this PR has been replaced with #1270.

**Comment by julien-c** [comment]
Awesome.

**Comment by zzusunjs** [comment]
> Do I have to use cli to generate the code?
Hi, jackalcooper. Did you fix the problem ? Could you please show some code snippets about how to load .pbtxt file with protobuf.js ? 🙏🙏

**Pull request closed without merging**
