### PR TITLE
deps: set @types/node to >=

### PR DESCRIPTION
**Pull request by indutny**
When using `protobuf.js` as a dependency in a project it is important
that `@types/node` package gets de-duped and has the same version as for
the rest of the modules in the project. Otherwise, typing conflicts
could happen as they do between v13 and v14 node types.

### CODE REVIEW

**Comment by indutny** [comment]
I'm happy with changing it to 14 as well, but I think `*` is more future proof. Btw, I'd greatly appreciate if a release could be made for this change since otherwise I'll have to add my fork as a dependency.

**Comment by alexander-fenster** [comment]
We discussed it and we think it might be a little bit more permissive than needed, would it be OK if we make it `>=13.7.0` instead? We can surely make a release with this change if needed.

**Comment by indutny** [comment]
Totally! This sounds great!

**Review by alexander-fenster — APPROVED** [review]

**Comment by indutny** [comment]
Awesome. Thanks a lot!

**Pull request merged**
