### PR TITLE
fix(deps): patch minimatch vulnerability

### LINKED ISSUE #1696: cli/package-lock.json forces insecure minimatch 3.0.4
protobuf.js version: 6.11.2

Upon installing the package, the cli subpackage brings in (via transitive dep) minimatch 3.0.4. This version has been flagged with a security vulnerability. A version 3.0.5 (or higher) resolves the vulnerability, but cannot be installed via npm update due to cli/package-lock.json.

At this time the latest 3.x version is minimatch 3.1.2.

- Vulnerability reported by JFrog Xray: XRAY-198521
- Vulnerable Component: minimatch:3.0.4
- Severity: High
- CVSS Score: 4.3 (v2) 7.5 (v3)
- Fix version: 3.0.5
- Summary: minimatch minimatch.js braceExpand() Function Improper Regular Expression DoS
- Description: minimatch contains a flaw in the braceExpand() function in minimatch.js that is triggered as an improper regular expression is used to match patterns for brace expansion. This may allow a context-dependent attacker to hang or slow down a Node process using the library.

```
# in a dummy 't' project where protobufjs is the only installed package...

$ npm ls minimatch
t@1.0.0 (...omitted path...)/t
└── (empty)

$ cd node_modules/protobufjs/cli
$ npm ls minimatch
cli@6.9.0 (...omitted path...)/t/node_modules/protobufjs/cli
└─┬ tmp@0.2.1
  └─┬ rimraf@3.0.2
    └─┬ glob@7.1.6
      └── minimatch@3.0.4
```

### LINKED ISSUE #1697: minimatch minimatch.js braceExpand() Function Improper Regular Expression DoS
protobuf.js version: 6.11.2

The above mentioned version of protobufjs includes minimatch3.0.4 which has below high severity security issue:
minimatch contains a flaw in the braceExpand() function in minimatch.js that is triggered as an improper regular expression is used to match patterns for brace expansion. This may allow a context-dependent attacker to hang or slow down a Node process using the library.
If we change the version of minimatch to 3.0.5 or above then this could be resolved.
Can this be fixed in the next available release of protobufjs.

### LINKED ISSUE #1698: minimatch security vulnerability in CLI - only way to fix it is to delete cli folder contents
protobuf.js version: 6.11.2

Expected Behavior: Protobuf.js passes all security scans and vulnerability checks.
Actual Behavior: It fails our scans repeatedly because of a known minimatch 3.0.4 (or lower) security vulnerability.

Additional notes:  Because of the way the cli is packaged (lock file + node_modules folder), we are unable to cleanse the problem through conventional means.  (npm overrides or yarn resolutions for instance).  We do not use the CLI for production runtimes, but because of the way protobufjs is packaged, the cli and its vulnerability end up in the production image.

### PR DESCRIPTION
**Pull request by richgerrard**
If I follow this, glob packages minimatch.  Minimatch released a fix, glob also has a newer build, picking this up should pick up that.
Fixes #1696
Fixes #1697
Fixes #1698

### CODE REVIEW

**Comment by richgerrard** [comment]
@alexander-fenster 
Hi! Is this repo actively maintained anymore? Cheers,
-R

**Comment by richgerrard** [comment]
@dcodeIO @nicolasnoble 
Hi! Is this repo actively maintained anymore? Cheers,
-R

**Comment by alexander-fenster** [comment]
Hi @richgerrard, sorry, I don't have a contributor access to this repo. @dcodeIO is the repository owner who could help with this. Thank you!

**Comment by nicolasnoble** [comment]
Sorry, but unfortunately, I no longer have publishing nor writing privileges either. You'll have to ask @dcodeIO what their plans are for this project.

**Comment by jaehnri** [comment]
Hi! Friendly pinging @dcodeIO as this PR would be really helpful to me. Thanks!

**Review by alexander-fenster — APPROVED** [review]

**Comment by alexander-fenster** [comment]
Alright, thanks to @dcodeIO, I can merge this one now. We will release the update to 6.x soon.

**Pull request merged**
