### PR TITLE
Fix to allow comments above multi-line method declarations to be parsed.

### PR DESCRIPTION
**Pull request by timc88**
Fix for issue https://github.com/protobufjs/protobuf.js/issues/1200. Gets the comment above the method as soon as the method parsing starts.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Thanks for the fix @timc88 :) We had a blip when this was submitted, and CI didn't get run.  Would you mind rebasing, and pushing again to force TravisCI to run?  Thank you!

**Comment by timc88** [comment]
Hello @JustinBeckwith, thanks for reaching out. I'm a bit confused, do you want me to sync my fork and then make a new pull request? I don't think I have permission to push.

**Comment by JustinBeckwith** [comment]
Oh sorry! I just wanted you to push another small change to your own branch to bump the CI :)

**Comment by timc88** [comment]
Thanks! I synced my fork and it looks like that triggered CI, which seems to have passed. Hopefully that's what was needed. Let me know if you need anything else from me, and you should also theoretically have permission to edit my PR if necessary.

**Comment by timc88** [comment]
Hi @JustinBeckwith, just wanted to check in about this again. I reverted changes to generated files and the version bump in this pull request so it's just the code changes now, and CI appears to have completed successfully. Looks like it only needs a review now.

**Pull request merged**
